---
- hosts: all
  become: true # use sudo
  #become_method: su
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  tasks:
    - include_tasks: tasks/nfs.yml
      vars:
        nfs_services_source: "192.168.1.37:/volume1/services"
        nfs_mount_services_path: "/mnt/services"
        nfs_music_source: "192.168.1.37:/volume1/music"
        nfs_mount_music_path: "/mnt/music"
        nfs_video_source: "192.168.1.37:/volume1/video"
        nfs_mount_video_path: "/mnt/video"
    - include_tasks: tasks/mediaplayers.yml
      vars:
        nfs_mount_services_path: "/mnt/services"
        nfs_mount_music_path: "/mnt/music"
        nfs_mount_video_path: "/mnt/video"
    - include_tasks: tasks/portainer.yml