---
- hosts: all
  become: true # use sudo
  #become_method: su
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  tasks:
    - include_tasks: tasks/nfs.yml
      vars:
        nfs_source: "192.168.1.36:/volume1/test"
        nfs_mount_path: "/mnt/nas"
    - include_tasks: tasks/mediaplayers.yml
      vars:
        nfs_mount_path: "/mnt/nas"
    - include_tasks: tasks/portainer.yml