- name: Create a directory if it does not exist for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "{{ nfs_mount_services_path }}/jellyfin/config"
    #- "{{ nfs_mount_services_path }}/plex/config"
    - "{{ nfs_mount_services_path }}/xteve/config"
    - /opt/docker/volumes/plex/config

#- name: Copy plex config default if not exist
#  ansible.builtin.copy:
#    src: "{{ nfs_mount_services_path }}/plex"
#    dest: /opt/docker/volumes/plex
#    remote_src: true
#    force: false

- name: Install Jellyfin
  community.docker.docker_container:
    name: jellyfin
    image: linuxserver/jellyfin:10.8.9
    restart_policy: unless-stopped
    volumes:
      - "{{ nfs_mount_services_path }}/jellyfin/config:/config"
      - "{{ nfs_mount_services_path }}:/data/services"
      - "{{ nfs_mount_music_path }}:/data/music"
      - "{{ nfs_mount_video_path }}:/data/video"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    ports:
      - 8096:8096
    devices: 
      - /dev/dri:/dev/dri

- name: Install Plex
  community.docker.docker_container:
    name: plex
    image: linuxserver/plex:1.31.1
    network_mode: host
    restart_policy: unless-stopped
    volumes:
      - /opt/docker/volumes/plex/config:/config
      - "{{ nfs_mount_services_path }}:/data/services"
      - "{{ nfs_mount_video_path }}:/data/video"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      VERSION: docker
      #PLEX_CLAIM: 
    ports:
      - 32400:32400
    devices: 
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

- name: Install XTeVe
  community.docker.docker_container:
    name: xteve
    image: senexcrenshaw/xteve:2.5.3
    network_mode: host
    restart_policy: unless-stopped
    volumes:
      - "{{ nfs_mount_services_path }}/xteve/config:/home/xteve/conf"
    env:
      TZ: Etc/UTC
    ports:
      - 34400:34400