- name: Install Portainer
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:2.17.1-alpine
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env:
      TZ: Etc/UTC
    ports:
      - 9000:9000
      - 9443:9443